/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_user_interface;

import study_item_objects.AnswerDataContainer;
import common.Logger;
import dictionary.CardContainer;
import dictionary.DictionaryDataModificator;
import dictionary.CardChooser;
import dictionary.CardTester;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import settings_handler.SettingsHandler;

/**
 *
 * @author varga
 */
public class CardTesterDialog extends javax.swing.JDialog {

    private final CardTester cardTester = new CardTester();
    private final CardContainer cardContainer = new CardContainer();
    private final AnswerDataContainer answerDataContainer = new AnswerDataContainer();
    private final DefaultTableModel model;
    private final Logger logger = new Logger();
    private long startTime;
    private long finishTime;
    
    public CardTesterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        
        jTextField1.requestFocus();
        
        model = (DefaultTableModel)jTable1.getModel();
        
        SettingsHandler settingsHandler = new SettingsHandler();
        
        cardContainer.loadDataFromFile(settingsHandler.getStudiedLanguageCardDataPath());
        answerDataContainer.loadDataFromFile(settingsHandler.getStudiedLanguageAnswerDataPath());
        
        CardChooser cardChooser = new CardChooser();
        cardChooser.setCardContainer(cardContainer);
        cardChooser.setAnswerDataContainer(answerDataContainer);
        Set<Integer> cardIndexesToTest = cardChooser.chooseCardsToTestIndexesForTest8();
        //Set<Integer> cardIndexesToTest = cardChooser.getRandomCardIndexes(3, new HashSet<Integer>());    //for test
        
        cardTester.setAllCard(cardContainer);
        cardTester.setCardsToTestFromCardIndexesSet(cardIndexesToTest);
        
        cardTester.moveToNextCardToQuestion();
  
        jTextField3.setText(cardTester.getActualQuestionedCard().definition);
        jTextField1.setText("");
        jTextField2.setText("");
        jLabel1.setText("");
        jLabel2.setText(cardTester.numberOfCardsQuestioned()+ "\\" + cardTester.getNumberOfQuestions());
        
        jButton1.setMnemonic(KeyEvent.VK_B);
        
        startTime = new Date().getTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 0, 0));
        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jButton2.setText("Inspect card");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Term", "Definition"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!cardTester.isGetAnswerToActualQuestion()) {

                cardTester.setUserAnswer(jTextField1.getText());

                if (cardTester.getActualQuestionedCard().term.equals(cardTester.getUserActualAnswer())) {
                    if (cardTester.isMoreCardToTest()) {
                        cardTester.moveToNextCardToQuestion();
                        jLabel2.setText(cardTester.numberOfCardsQuestioned()+ "\\" + cardTester.getNumberOfQuestions());
                            jTextField3.setText(cardTester.getActualQuestionedCard().definition);
                            jTextField1.setText("");
                            jTextField2.setText("");
                            jLabel1.setText("");
                    }
                    else {
                        goToStatisticsFrameAndSaveData();
                        dispose();
                    }
                }
                else {
                    if (cardTester.isUserAnswerRight()) {
                        jTextField1.setText("");
                        jTextField2.setText(cardTester.getActualQuestionedCard().term);
                        jTextField2.setForeground(new java.awt.Color(45, 107, 53));
                        jLabel1.setText("RIGHT, but the above term was tought");

                        showAcceptableCards();
                    }
                    else {
                        jTextField1.setText("");
                        jTextField2.setText(cardTester.getActualQuestionedCard().term);
                        jTextField2.setForeground(new java.awt.Color(255, 0, 0));
                        jLabel1.setText("wrong");

                        showAcceptableCards();
                    }
                }
            }
            else {
                if (cardTester.getActualQuestionedCard().term.equals(jTextField1.getText())) {
                    if (cardTester.isMoreCardToTest()) {
                        cardTester.moveToNextCardToQuestion();
                        jLabel2.setText(cardTester.numberOfCardsQuestioned()+ "\\" + cardTester.getNumberOfQuestions());
                        jTextField3.setText(cardTester.getActualQuestionedCard().definition);
                        jTextField1.setText("");
                        jTextField2.setText("");
                        jLabel1.setText("");

                        clearTabular();
                    }
                    else {
                        goToStatisticsFrameAndSaveData();
                        dispose();
                    }
                }
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void showAcceptableCards() {
        Set<Integer> acceptableCardIndexes 
                = cardTester.getAcceptableCardIndexes(cardTester.getActualQuestionedCard().definition);
        
        for (int index : acceptableCardIndexes) {
            model.addRow(new Object[] {
                        cardContainer.getCardByIndex(index).term, 
                        cardContainer.getCardByIndex(index).definition
            });
        }
    }
    
    private void clearTabular() {
        for (int i=model.getRowCount()-1; 0<=i; i--) {
            model.removeRow(i);
        }
    }
    
    private void goToStatisticsFrameAndSaveData() {
        finishTime = new Date().getTime();
        
        AnswerDataContainer userAnswers = cardTester.getUserAnswers();
        
        DictionaryDataModificator dictionaryDataModificator = new DictionaryDataModificator();
	dictionaryDataModificator.setCardContainer(cardContainer);
	dictionaryDataModificator.setAnswerDataContainer(answerDataContainer);
        
	dictionaryDataModificator.appendToStudiedLanguageCardData(userAnswers);
        
        
        CardTesterStatisticsDialog dialog = new CardTesterStatisticsDialog(new javax.swing.JFrame(), true);
        dialog.allCard = cardContainer;
        dialog.testAnswers = cardTester.getUserAnswers();
        dialog.oldAnswers = answerDataContainer;
        dialog.finishTime = finishTime;
        dialog.startTime = startTime;
        
        dialog.setCardTestStatisticsDataToFrame();
        dialog.setVisible(true);
    }
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CardTesterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CardTesterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CardTesterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CardTesterDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CardTesterDialog dialog = new CardTesterDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
