/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphic_user_interface;

import common.AnswerDataContainer;
import common.Logger;
import dictionary.CardContainer;
import dictionary.DictionaryDataModificator;
import experimental_classes.CardChooser2;
import experimental_classes.CardTestStatisticsMaker2;
import experimental_classes.CardTester2;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import java.util.Set;
import settings_handler.SettingsHandler;

/**
 *
 * @author varga
 */
public class NewJDialog extends javax.swing.JDialog {

    private CardTester2 cardTester2 = new CardTester2();
    private CardTestStatisticsMaker2 cardTestStatisticsMaker = new CardTestStatisticsMaker2();
    private CardContainer cardContainer = new CardContainer();
    private AnswerDataContainer answerDataContainer = new AnswerDataContainer();
    private Logger logger = new Logger();
    
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        
        jTextField1.requestFocus();
        
        SettingsHandler settingsHandler = new SettingsHandler();
        
        cardContainer.loadDataFromFile(settingsHandler.getStudiedLanguageCardDataPath());
        answerDataContainer.loadDataFromFile(settingsHandler.getStudiedLanguageAnswerDataPath());
        
        CardChooser2 cardChooser = new CardChooser2();
        cardChooser.setCardContainer(cardContainer);
        cardChooser.setAnswerDataContainer(answerDataContainer);
        Set<Integer> cardIndexesToTest = cardChooser.chooseCardsToTestIndexesForTest8();
        //Set<Integer> cardIndexesToTest = cardChooser.getRandomCardIndexes(3, new HashSet<Integer>());    //for test
        
        CardContainer cardContainer2 = new CardContainer();
        for (int index : cardIndexesToTest) {
            cardContainer2.addCard(cardContainer.getCardByIndex(index));
        }
        
        cardTester2.setCardsToTest(cardContainer2);
        cardTester2.setAllCard(cardContainer);
        
        cardTester2.moveToNextCardToQuestion();
  
        jTextField3.setText(cardTester2.getActualQuestionedCard().definition);
        jTextField1.setText("");
        jTextField2.setText("");
        jLabel1.setText("");
        jLabel2.setText(cardTester2.numberOfCardsQuestioned()+ "\\" + cardTester2.getNumberOfQuestions());
        
        jButton1.setMnemonic(KeyEvent.VK_B);
        
        cardTestStatisticsMaker.startMeasureTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        jLabel1.setText("jLabel1");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 0, 0));
        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jButton2.setText("Inspect card");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!cardTester2.isGetAnswerToActualQuestion()) {

                cardTester2.setUserAnswer(jTextField1.getText());

                if (cardTester2.getActualQuestionedCard().term.equals(cardTester2.getUserActualAnswer())) {
                    if (cardTester2.isMoreCardToTest()) {
                        cardTester2.moveToNextCardToQuestion();
                        jLabel2.setText(cardTester2.numberOfCardsQuestioned()+ "\\" + cardTester2.getNumberOfQuestions());
                            jTextField3.setText(cardTester2.getActualQuestionedCard().definition);
                            jTextField1.setText("");
                            jTextField2.setText("");
                            jLabel1.setText("");
                        }
                        else {
                            goToStatisticsFrameAndSaveData();
                            dispose();
                        }
                    }
                    else {
                        if (cardTester2.isUserAnswerRight()) {
                            jTextField1.setText("");
                            jTextField2.setText(cardTester2.getActualQuestionedCard().term);
                            jTextField2.setForeground(new java.awt.Color(45, 107, 53));
                            jLabel1.setText("RIGHT, but the above term was tought");
                        }
                        else {
                            jTextField1.setText("");
                            jTextField2.setText(cardTester2.getActualQuestionedCard().term);
                            jTextField2.setForeground(new java.awt.Color(255, 0, 0));
                            jLabel1.setText("wrong");
                        }
                    }
                }
                else {
                    if (cardTester2.getActualQuestionedCard().term.equals(jTextField1.getText())) {
                        if (cardTester2.isMoreCardToTest()) {
                            cardTester2.moveToNextCardToQuestion();
                            jLabel2.setText(cardTester2.numberOfCardsQuestioned()+ "\\" + cardTester2.getNumberOfQuestions());
                                jTextField3.setText(cardTester2.getActualQuestionedCard().definition);
                                jTextField1.setText("");
                                jTextField2.setText("");
                                jLabel1.setText("");
                            }
                            else {
                                goToStatisticsFrameAndSaveData();
                                dispose();
                            }
                        }
                    }
                }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void goToStatisticsFrameAndSaveData() {
        cardTestStatisticsMaker.endMeasureTime();
        
        AnswerDataContainer userAnswers = cardTester2.getUserAnswers();
        
        cardTestStatisticsMaker.setTestAnswers(userAnswers);
        cardTestStatisticsMaker.setTestedCards(cardTester2.getCardsToTest());
        cardTestStatisticsMaker.setOldAnswers(answerDataContainer);
        
        DictionaryDataModificator dictionaryDataModificator = new DictionaryDataModificator();
	dictionaryDataModificator.setCardContainer(cardContainer);
	dictionaryDataModificator.setAnswerDataContainer(answerDataContainer);
        
	dictionaryDataModificator.appendToStudiedLanguageCardData(userAnswers);

        logger.debug("appended answers:\n" + userAnswers.toString());
        
        NewJDialog2 dialog = new NewJDialog2(new javax.swing.JFrame(), true);
        dialog.setCardTestStatisticsMaker(cardTestStatisticsMaker);
        dialog.setCardTestStatisticsDataToFrame();
        dialog.setVisible(true);
    }
    
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
