package graphic_user_interface.dictionary;

import common.Logger;
import dictionary.Card;
import dictionary.DictionaryDataContainer;
import graphic_user_interface.common.DialogAnswer;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

public class CardInspectorPanel extends javax.swing.JPanel {

    public Integer cardIndex = -1;
    private Set<Integer> categories = new HashSet<>();
    
    public DictionaryDataContainer dictionaryDataContainer;
    
    private final DefaultTableModel tableModel;
    
    private Logger logger = new Logger();    
    
    public CardInspectorPanel() {
        initComponents();
        
        tableModel = (DefaultTableModel)jTable1.getModel();

        
        jTextField1.setText("");
        jTextField2.setText("");
        
        addExampleSentenceButton.setMnemonic(KeyEvent.VK_A);
        deleteExampleSentenceButton.setMnemonic(KeyEvent.VK_E);
        modificateExampleSentenceButton.setMnemonic(KeyEvent.VK_M);
        setCardCategoriesButton.setMnemonic(KeyEvent.VK_T);
        
        jTextField1.requestFocus();
    }

    public void setDataFromCard(Card card) {
        cardIndex = card.index;
        jTextField1.setText(card.term);
        jTextField2.setText(card.definition);
        
        for (String exampleSentence : card.exampleSentences) {
            tableModel.addRow(new Object[]{exampleSentence});
        }
        
        for (int categoryIndex : card.categoryIndexes) { 
            categories.add(categoryIndex);
            jComboBox1.addItem(
                    dictionaryDataContainer.getCategoryContainer()
                            .getCategoryNameByIndex(categoryIndex));
        }
    }
    
    public Card getCardData() {
        Card card = new Card();
        card.index = cardIndex;
        card.term = jTextField1.getText();
        card.definition = jTextField2.getText();
        card.categoryIndexes = categories;
        
        for (int i=0; i<tableModel.getRowCount(); i++) {
            String exampleSentence = (String)tableModel.getValueAt(i, 0);
            card.exampleSentences.add(exampleSentence);
        }

        return card;
    }
    
    public String getTerm() {
        return jTextField1.getText();
    }
    
    public String getDefinition() {
        return jTextField2.getText();
    }
    
    public List<String> getExampleSentences() {
        List<String> out = new ArrayList<>();
        
        for (int i = 0; i<tableModel.getRowCount(); i++) {
            out.add((String)tableModel.getValueAt(i, 0));
        }
        
        return out;
    }
    
    public Set<Integer> getCategories() {
        return categories;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteExampleSentenceButton = new javax.swing.JButton();
        addExampleSentenceButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        modificateExampleSentenceButton = new javax.swing.JButton();
        setCardCategoriesButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        deleteExampleSentenceButton.setText("Delete sentence");
        deleteExampleSentenceButton.setEnabled(false);
        deleteExampleSentenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteExampleSentenceButtonActionPerformed(evt);
            }
        });

        addExampleSentenceButton.setText("Add sentence");
        addExampleSentenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExampleSentenceButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("categories:");

        modificateExampleSentenceButton.setText("Modificate sentence");
        modificateExampleSentenceButton.setEnabled(false);
        modificateExampleSentenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificateExampleSentenceButtonActionPerformed(evt);
            }
        });

        setCardCategoriesButton.setText("Set card categories");
        setCardCategoriesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCardCategoriesButtonActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField1.setText("jTextField1");

        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField2.setText("jTextField2");

        jLabel1.setText("term:");

        jLabel2.setText("definition:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Example sentences"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable1FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setCardCategoriesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(addExampleSentenceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modificateExampleSentenceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteExampleSentenceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(setCardCategoriesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addExampleSentenceButton)
                    .addComponent(modificateExampleSentenceButton)
                    .addComponent(deleteExampleSentenceButton))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteExampleSentenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteExampleSentenceButtonActionPerformed
        int selectedTableRowIndex = jTable1.getSelectedRow();
        tableModel.removeRow(selectedTableRowIndex);

        deleteExampleSentenceButton.setEnabled(false);
        modificateExampleSentenceButton.setEnabled(false);
    }//GEN-LAST:event_deleteExampleSentenceButtonActionPerformed
     
    private void addExampleSentenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExampleSentenceButtonActionPerformed
        DialogAnswer addSentenceDialogAnswer = new DialogAnswer();
        AddExampleSentenceDialog dialog = new AddExampleSentenceDialog(new javax.swing.JFrame(), true);
        dialog.dialogAnswer = addSentenceDialogAnswer;
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        if (addSentenceDialogAnswer.boolAnswer) {
            tableModel.addRow(new Object[]{
                addSentenceDialogAnswer.stringAnswer
            });
            
            deleteExampleSentenceButton.setEnabled(false);
            modificateExampleSentenceButton.setEnabled(false);
        }
    }//GEN-LAST:event_addExampleSentenceButtonActionPerformed

    private void modificateExampleSentenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificateExampleSentenceButtonActionPerformed
        DialogAnswer modificateSentenceDialogAnswer = new DialogAnswer();
        int selectedTableRowIndex = jTable1.getSelectedRow();
        ModificateExampleSentenceDialog dialog 
                = new ModificateExampleSentenceDialog(new javax.swing.JFrame(), true);
        dialog.dialogAnswer = modificateSentenceDialogAnswer;
        dialog.setExampleSentenceToModificate(
                (String)tableModel.getValueAt(selectedTableRowIndex,0));
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);

        if (modificateSentenceDialogAnswer.boolAnswer) {
            tableModel.removeRow(selectedTableRowIndex);
            tableModel.insertRow(selectedTableRowIndex, new Object[]{
                    modificateSentenceDialogAnswer.stringAnswer});
            
            deleteExampleSentenceButton.setEnabled(false);
            modificateExampleSentenceButton.setEnabled(false);
        }
    }//GEN-LAST:event_modificateExampleSentenceButtonActionPerformed

    private void jTable1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable1FocusGained
        deleteExampleSentenceButton.setEnabled(true);
        modificateExampleSentenceButton.setEnabled(true);
    }//GEN-LAST:event_jTable1FocusGained

    private void setCardCategoriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCardCategoriesButtonActionPerformed
        SetCardCategoryDialog dialog 
                = new SetCardCategoryDialog(new javax.swing.JFrame(), true);
        dialog.setAllCategories(dictionaryDataContainer.getCategoryContainer());
        dialog.setSelectedCategories(categories);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        
        jComboBox1.removeAllItems();
        for (int categoryIndex : categories) {
            jComboBox1.addItem(
                    dictionaryDataContainer.getCategoryContainer()
                            .getCategoryNameByIndex(categoryIndex));
        }
    }//GEN-LAST:event_setCardCategoriesButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addExampleSentenceButton;
    private javax.swing.JButton deleteExampleSentenceButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton modificateExampleSentenceButton;
    private javax.swing.JButton setCardCategoriesButton;
    // End of variables declaration//GEN-END:variables
}
