package graphic_user_interface.dictionary;

import dictionary.Card;
import dictionary.CardContainer;
import dictionary.CardFinder;
import disc_operation_handlers.DictionaryDataModificator;
import disc_operation_handlers.LanguageFilesDataHandler;
import graphic_user_interface.common.DialogAnswer;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import study_item_objects.AnswerDataContainer;

public class DictionaryDialog extends javax.swing.JDialog {

    private CardContainer cardContainer;
    private AnswerDataContainer answerDataContainer;
    
    private final CardFinder cardFinder = new CardFinder();
    private final DefaultTableModel tableModel;
    private final DefaultTableModel lastSearchesTableModel;
    
    private LanguageFilesDataHandler languageFilesDataHandler
            = new LanguageFilesDataHandler();
    
    private Vector<Card> listedCards;
   
    public DictionaryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
        
        tableModel = (DefaultTableModel)jTable1.getModel();
        lastSearchesTableModel = (DefaultTableModel)jTable2.getModel();
        
        //table rows are not editable but can be selected
        JTextField tf = new JTextField();
        tf.setEditable(false);
        DefaultCellEditor editor = new DefaultCellEditor( tf );
        jTable1.setDefaultEditor(Object.class, editor);
        
        jTextField1.setText("");
        jTextField1.requestFocus();
        jLabel1.setText("-");
        
        jComboBox1.removeAllItems();
        jComboBox1.addItem(languageFilesDataHandler.getStudiedLanguageName().toLowerCase()
                + " -> hungarian");
        jComboBox1.addItem("hungarian -> " +
                languageFilesDataHandler.getStudiedLanguageName().toLowerCase());

        jButton1.setMnemonic(KeyEvent.VK_C);
        addNewCardButton.setMnemonic(KeyEvent.VK_A);
        modificateCardButton.setMnemonic(KeyEvent.VK_M);
        deleteCardButton.setMnemonic(KeyEvent.VK_D);
    }

    public void initialise() {
        cardFinder.setCardContainer(cardContainer);
    }
    
    public void setCardContainer(CardContainer a) {
        cardContainer = a;
    }
    
    public void setAnswerDataContainer(AnswerDataContainer a) {
        answerDataContainer = a;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        modificateCardButton = new javax.swing.JButton();
        deleteCardButton = new javax.swing.JButton();
        addNewCardButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "term", "definition"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField1.setText("jTextField1");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "foreign -> hungarian", "hungarian -> foreign" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        modificateCardButton.setText("Modificate selected card");
        modificateCardButton.setEnabled(false);
        modificateCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificateCardButtonActionPerformed(evt);
            }
        });

        deleteCardButton.setText("Delete card");
        deleteCardButton.setEnabled(false);
        deleteCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCardButtonActionPerformed(evt);
            }
        });

        addNewCardButton.setText("Add new card");
        addNewCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewCardButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("number of results found:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Last searches"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addNewCardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modificateCardButton)
                            .addComponent(deleteCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addNewCardButton, deleteCardButton, jButton1, jScrollPane2, modificateCardButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addNewCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificateCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteCardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER &&
                !jTextField1.getText().isEmpty()) {
            
            clearTable();

            if (jComboBox1.getSelectedIndex() == 0) {
                listedCards
                        = cardFinder.getCardsWithGivenTermPart(jTextField1.getText());
            }

            if (jComboBox1.getSelectedIndex() == 1) {
                listedCards
                        = cardFinder.getCardsWithGivenDefinitionPart(jTextField1.getText());
            }

            toScreenListedCards();
            
            lastSearchesTableModel.insertRow(0,new Object[]{
                    jTextField1.getText()});
            
            jTextField1.setText("");
            modificateCardButton.setEnabled(false);
            deleteCardButton.setEnabled(false);
        }
        else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER &&
                jTextField1.getText().isEmpty()) {
                clearTable();
                modificateCardButton.setEnabled(false);
                deleteCardButton.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void clearTable() {
        for (int i=tableModel.getRowCount()-1; 0<=i; i--) {
            tableModel.removeRow(i);
        }
        jLabel1.setText("-");
    }
    
    private void deleteRowFromTable(int rowIndex) {
        tableModel.removeRow(rowIndex);
        jLabel1.setText(Integer.toString(tableModel.getRowCount()));
    }

    private void toScreenListedCards() {
        if (jComboBox1.getSelectedIndex() == 0) {
            for (int i = 0; i < listedCards.size(); i++) {
                tableModel.addRow(new Object[]{
                    listedCards.get(i).term,
                    listedCards.get(i).definition});
            }
        }

        if (jComboBox1.getSelectedIndex() == 1) {
            for (int i = 0; i < listedCards.size(); i++) {
                tableModel.addRow(new Object[]{
                    listedCards.get(i).definition,
                    listedCards.get(i).term});
            }
        }
        
        jLabel1.setText(Integer.toString(listedCards.size()));
    }
    
    private void modificateCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificateCardButtonActionPerformed
        int selectedTableRowIndex = jTable1.getSelectedRow();
        Card cardToModificate = listedCards.get(selectedTableRowIndex);
        
        CardModificatorDialog dialog 
                = new CardModificatorDialog(new javax.swing.JFrame(), true);
        dialog.cardContainer = cardContainer;
        dialog.cardToModificate = cardToModificate;
        dialog.initialise();
        dialog.setVisible(true);
        
        tableModel.setValueAt(cardToModificate.term, selectedTableRowIndex, 0);
        tableModel.setValueAt(cardToModificate.definition, selectedTableRowIndex, 1);
        
        jTextField1.requestFocus();
    }//GEN-LAST:event_modificateCardButtonActionPerformed

    private void addNewCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewCardButtonActionPerformed
        clearTable();
        
        CardAdderDialog dialog = new CardAdderDialog(new javax.swing.JFrame(), true);
        dialog.setCardContainer(cardContainer);
        dialog.setVisible(true);
        
        jTextField1.requestFocus();
    }//GEN-LAST:event_addNewCardButtonActionPerformed

    private void deleteCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCardButtonActionPerformed
        int selectedTableRowIndex = jTable1.getSelectedRow();
        Card cardToDelete = listedCards.get(selectedTableRowIndex);
        
        CardDeleteReinforceDialog dialog 
                = new CardDeleteReinforceDialog(new javax.swing.JFrame(), true);
        DialogAnswer dialogAnswer = new DialogAnswer();
        dialog.dialogAnswer = dialogAnswer;
        dialog.cardToDelete = cardToDelete;
        dialog.initialise();
        dialog.setVisible(true);
        
        if (dialogAnswer.answer) {
            DictionaryDataModificator dictionaryDataModificator 
                    = new DictionaryDataModificator();
            dictionaryDataModificator.setCardContainer(cardContainer);
            dictionaryDataModificator.setAnswerDataContainer(answerDataContainer);
            dictionaryDataModificator.removeCardWithAnswersByCardIndex(cardToDelete.index);
            
            modificateCardButton.setEnabled(false);
            deleteCardButton.setEnabled(false);
            
            deleteRowFromTable(selectedTableRowIndex);
        }
        
                jTextField1.requestFocus();
    }//GEN-LAST:event_deleteCardButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        modificateCardButton.setEnabled(true);
        deleteCardButton.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //setFormForNextQuery();
        
        JTableHeader th = jTable1.getTableHeader();
        TableColumnModel tcm = th.getColumnModel();
        TableColumn tc0 = tcm.getColumn(0);
        TableColumn tc1 = tcm.getColumn(1);
        
        if( jComboBox1.getSelectedIndex() == 0) {
            tc0.setHeaderValue("term");
            tc1.setHeaderValue("definition");
        }
        
        if( jComboBox1.getSelectedIndex() == 1) {
            tc0.setHeaderValue("definition");
            tc1.setHeaderValue("term");
        }
        
        th.repaint();
        
        clearTable();
        
        jTextField1.requestFocus();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DictionaryDialog dialog = new DictionaryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewCardButton;
    private javax.swing.JButton deleteCardButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton modificateCardButton;
    // End of variables declaration//GEN-END:variables
}
