package graphic_user_interface.grammar_book;

import graphic_user_interface.common.DialogAnswer;
import common.Logger;
import grammar_book.*;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class GrammarBookModificatorDialog extends javax.swing.JDialog {

    public GrammarBook grammarBook;
    
    private final DefaultTreeModel treeModel;
    private Logger logger = new Logger();
    
    private int selectedGrammarItemIndex;
    private DefaultMutableTreeNode selectedNode;
    
    public GrammarBookModificatorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        closeButton.setMnemonic(KeyEvent.VK_C);
        deleteGrammarItemButton.setMnemonic(KeyEvent.VK_D);
        addGrammarItemButton.setMnemonic(KeyEvent.VK_A);
 
        treeModel = (DefaultTreeModel) jTree1.getModel();
    }

    public void setGrammarBook(GrammarBook grammarBook) {
        this.grammarBook = grammarBook;
    }
    
    private void fillTreeWithGrammarBookData() {
        
        GrammarItemContainer grammarItemContainer = grammarBook.dataContainer.getGrammarItemContainer();
        
        for (int i=0; i<grammarItemContainer.numberOfGrammarItems(); i++) {
            GrammarItemTitle grammarItemTitle = grammarItemContainer.getGrammarItemByOrder(i).title;
            Vector<String> categoris = grammarItemTitle.getCategorisInVector();
            
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeModel.getRoot();
            
            for (int j=0; j<categoris.size(); j++) {
                
                GrammarBookReaderTreeNodeUSerObject nodeUserObj
                        = new GrammarBookReaderTreeNodeUSerObject();
                
                nodeUserObj.caption = categoris.get(j);
                nodeUserObj.grammarItemIndex = grammarItemContainer.getGrammarItemByOrder(i).index;
                
                DefaultMutableTreeNode childNode = new DefaultMutableTreeNode(nodeUserObj);
                
                if (node.getChildCount() == 0) {
                    node.add(childNode);
                    node = childNode;
                }
                else {
                    if (!node.getLastChild().toString().equals(categoris.get(j))) {
                        node.add(childNode);
                        node = childNode;
                    }
                    else {
                        node = (DefaultMutableTreeNode) node.getLastChild();
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        addGrammarItemButton = new javax.swing.JButton();
        modificateGrammarItemButton = new javax.swing.JButton();
        deleteGrammarItemButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Grammar Book");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jTree1);

        addGrammarItemButton.setText("Add gramar item as child");
        addGrammarItemButton.setEnabled(false);
        addGrammarItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGrammarItemButtonActionPerformed(evt);
            }
        });

        modificateGrammarItemButton.setText("Modificate grammar item");
        modificateGrammarItemButton.setEnabled(false);
        modificateGrammarItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificateGrammarItemButtonActionPerformed(evt);
            }
        });

        deleteGrammarItemButton.setText("Delete grammar item");
        deleteGrammarItemButton.setEnabled(false);
        deleteGrammarItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGrammarItemButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Move grammar item to other categrory");
        jButton5.setEnabled(false);

        jButton7.setText("Add category as child");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Delete category");
        jButton8.setEnabled(false);

        jButton9.setText("Move grammar item in category");
        jButton9.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addGrammarItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modificateGrammarItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(deleteGrammarItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addGrammarItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modificateGrammarItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteGrammarItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged

        selectedNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        
        if (selectedNode != null) {
            if (selectedNode.isLeaf()) {
                deleteGrammarItemButton.setEnabled(true);
                modificateGrammarItemButton.setEnabled(true);
                addGrammarItemButton.setEnabled(false);

                GrammarBookReaderTreeNodeUSerObject nodeInfo 
                    = (GrammarBookReaderTreeNodeUSerObject)selectedNode.getUserObject();

                selectedGrammarItemIndex = nodeInfo.grammarItemIndex;
            }
            else {
                deleteGrammarItemButton.setEnabled(false);
                modificateGrammarItemButton.setEnabled(false);
                addGrammarItemButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTree1ValueChanged

    private void addGrammarItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGrammarItemButtonActionPerformed
        GrammarItemInspectorDialog dialog 
                = new GrammarItemInspectorDialog(new javax.swing.JFrame(), true);;
        dialog.setVisible(true);
    }//GEN-LAST:event_addGrammarItemButtonActionPerformed

    private void deleteGrammarItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGrammarItemButtonActionPerformed
        GrammarItemDeleteReinforceDialog dialog 
                = new GrammarItemDeleteReinforceDialog(new javax.swing.JFrame(), true);
        DialogAnswer dialogAnswer = new DialogAnswer();
        
        dialog.dialogAnswer = dialogAnswer;
        dialog.grammarItem = grammarBook.dataContainer
                .getGrammarItemContainer().getByIndex(selectedGrammarItemIndex);
        dialog.initialise();
        dialog.setVisible(true);

        if (dialogAnswer.boolAnswer) {
            grammarBook.dataModificator.deleteGrammarItemByIndex(selectedGrammarItemIndex);
            treeModel.removeNodeFromParent(selectedNode);
            deleteGrammarItemButton.setEnabled(false);
            modificateGrammarItemButton.setEnabled(false);
        }
    }//GEN-LAST:event_deleteGrammarItemButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void modificateGrammarItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificateGrammarItemButtonActionPerformed
        GrammarItemInspectorDialog dialog 
                = new GrammarItemInspectorDialog(new javax.swing.JFrame(), true);
        dialog.grammarItem = grammarBook.dataContainer
                .getGrammarItemContainer().getByIndex(selectedGrammarItemIndex);
        dialog.fillWidgetsWithGrammarItemData();
        dialog.setVisible(true);
    }//GEN-LAST:event_modificateGrammarItemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrammarBookModificatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrammarBookModificatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrammarBookModificatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrammarBookModificatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GrammarBookModificatorDialog dialog = new GrammarBookModificatorDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGrammarItemButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteGrammarItemButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton modificateGrammarItemButton;
    // End of variables declaration//GEN-END:variables
}
