package graphic_user_interface.grammar_book;

import common.Logger;
import disc_operation_handlers.GrammarDataModificator;
import disc_operation_handlers.LanguageFilesDataHendler;
import grammar_book.GrammarAnswerDataContainer;
import grammar_book.GrammarBook;
import grammar_book.GrammarItemTitle;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

public class GrammarBookModificatorDialog extends javax.swing.JDialog {

    public GrammarBook grammarBook;
    public GrammarAnswerDataContainer grammarAnswerDataContainer;
    public LanguageFilesDataHendler languageFilesDataHendler;
    
    private final GrammarDataModificator grammarDataModificator = new GrammarDataModificator();
    private final DefaultTreeModel treeModel;
    private Logger logger = new Logger();
    
    private int selectedGrammarItemIndex;
    private DefaultMutableTreeNode selectedNode;
    
    public GrammarBookModificatorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        
        jButton1.setMnemonic(KeyEvent.VK_B);
 
        treeModel = (DefaultTreeModel) jTree1.getModel();
    }

    public void initialise() {
        grammarDataModificator.setGrammarAnswerDataContainer(grammarAnswerDataContainer);
        grammarDataModificator.setGrammarBook(grammarBook);
        grammarDataModificator.setLanguageFilesDataHendler(languageFilesDataHendler);
        
        fillTreeWithGrammarBookData();
    }
    
    private void fillTreeWithGrammarBookData() {
        
        for (int i=0; i<grammarBook.numberOfGrammarItems(); i++) {
            GrammarItemTitle grammarItemTitle = grammarBook.getGrammarItemByOrder(i).title;
            Vector<String> categoris = grammarItemTitle.getCategorisInVector();
            
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) treeModel.getRoot();
            
            for (int j=0; j<categoris.size(); j++) {
                
                GrammarBookReaderTreeNodeUSerObject nodeUserObj
                        = new GrammarBookReaderTreeNodeUSerObject();
                
                nodeUserObj.caption = categoris.get(j);
                nodeUserObj.grammarItemIndex = grammarBook.getGrammarItemByOrder(i).index;
                
                DefaultMutableTreeNode childNode = new DefaultMutableTreeNode(nodeUserObj);
                
                if (node.getChildCount() == 0) {
                    node.add(childNode);
                    node = childNode;
                }
                else {
                    if (!node.getLastChild().toString().equals(categoris.get(j))) {
                        node.add(childNode);
                        node = childNode;
                    }
                    else {
                        node = (DefaultMutableTreeNode) node.getLastChild();
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        deleteGrammarItemButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        saveChangesButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Close without saving");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Grammar Book");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jTree1);

        jButton2.setText("Add gramar item as child");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Modificate grammar item");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        deleteGrammarItemButton.setText("Delete grammar item");
        deleteGrammarItemButton.setEnabled(false);
        deleteGrammarItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteGrammarItemButtonActionPerformed(evt);
            }
        });

        jButton5.setText("Move up in hierarchy");
        jButton5.setEnabled(false);

        saveChangesButton.setText("Save changes");
        saveChangesButton.setEnabled(false);
        saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesButtonActionPerformed(evt);
            }
        });

        jButton7.setText("Move down in hierarchy");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Move ahead in order");
        jButton8.setEnabled(false);

        jButton9.setText("Move back in order");
        jButton9.setEnabled(false);

        jButton4.setText("Reload data from disc");
        jButton4.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(deleteGrammarItemButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveChangesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteGrammarItemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveChangesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged

        selectedNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
        
        if (selectedNode != null) {
            if (selectedNode.isLeaf()) {
                deleteGrammarItemButton.setEnabled(true);
                jButton3.setEnabled(true);
                jButton2.setEnabled(false);

                GrammarBookReaderTreeNodeUSerObject nodeInfo 
                    = (GrammarBookReaderTreeNodeUSerObject)selectedNode.getUserObject();

                selectedGrammarItemIndex = nodeInfo.grammarItemIndex;
            }
            else {
                deleteGrammarItemButton.setEnabled(false);
                jButton3.setEnabled(false);
                jButton2.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jTree1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GrammarItemModificatorDialog dialog 
                = new GrammarItemModificatorDialog(new javax.swing.JFrame(), true);;
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteGrammarItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteGrammarItemButtonActionPerformed
        GrammarItemDeleteReinforceDialog dialog 
                = new GrammarItemDeleteReinforceDialog(new javax.swing.JFrame(), true);
        DialogAnswer dialogAnswer = new DialogAnswer();
        
        dialog.dialogAnswer = dialogAnswer;
        
        dialog.setVisible(true);

        if (dialogAnswer.answer) {
            grammarDataModificator.deleteGrammarItemByIndexFromMemory(selectedGrammarItemIndex);
            treeModel.removeNodeFromParent(selectedNode);
            saveChangesButton.setEnabled(true);
            deleteGrammarItemButton.setEnabled(false);
        }
    }//GEN-LAST:event_deleteGrammarItemButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
        //grammarDataModificator.writeDataToDisc();
        saveChangesButton.setEnabled(false);
    }//GEN-LAST:event_saveChangesButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GrammarItemModificatorDialog dialog 
                = new GrammarItemModificatorDialog(new javax.swing.JFrame(), true);;
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrammarBookModificatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrammarBookModificatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrammarBookModificatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrammarBookModificatorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GrammarBookModificatorDialog dialog = new GrammarBookModificatorDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteGrammarItemButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JButton saveChangesButton;
    // End of variables declaration//GEN-END:variables
}
